### ISSUE TITLE
NPE when buying shop items without stock

### ISSUE THREAD

**Issue by Akiranya** [divios/DailyShop#116]
Buying items **without** stock (i.e. those items with stock feature disabled) leads to NPE on the console, causing players can't buy items. Buying items **with** stock is fine, even tho the stock is zero.

The bug comes from this version: https://www.spigotmc.org/resources/dailyshop-an-advanced-shop-plugin.88768/update?update=446451
There was no problems with this version: https://www.spigotmc.org/resources/dailyshop-an-advanced-shop-plugin.88768/update?update=446066

```
[17:46:09] [Server thread/ERROR]: Could not pass event InventoryClickEvent to DailyShop v3.7
java.lang.NullPointerException: Cannot invoke "io.github.divios.lib.dLib.stock.dStock.get(org.bukkit.entity.Player)" because the return value of "io.github.divios.lib.dLib.shop.dShop.getStockForItem(String)" is null
	at io.github.divios.lib.dLib.shop.cashregister.preconditions.EnoughStockCondition.validate(EnoughStockCondition.java:14) ~[DailyShop-3.7.jar:?]
	at io.github.divios.lib.dLib.shop.cashregister.MultiplePreconditions.BuyPostconditions.lambda$validate$0(BuyPostconditions.java:28) ~[DailyShop-3.7.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.github.divios.lib.dLib.shop.cashregister.MultiplePreconditions.BuyPostconditions.validate(BuyPostconditions.java:28) ~[DailyShop-3.7.jar:?]
	at io.github.divios.lib.dLib.shop.cashregister.carts.BuyCart.validatePostConditions(BuyCart.java:88) ~[DailyShop-3.7.jar:?]
	at io.github.divios.lib.dLib.shop.cashregister.carts.BuyCart.checkOut(BuyCart.java:63) ~[DailyShop-3.7.jar:?]
	at io.github.divios.lib.dLib.confirmMenu.abstractConfirmMenu.lambda$createConfirmButton$5(abstractConfirmMenu.java:182) ~[DailyShop-3.7.jar:?]
	at io.github.divios.core_lib.inventory.ItemButton.onClick(ItemButton.java:65) ~[DailyShop-3.7.jar:?]
	at io.github.divios.core_lib.inventory.InventoryGUI.onClick(InventoryGUI.java:479) ~[DailyShop-3.7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor912.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1563]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2924) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1441) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1389) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1563]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by divios** [comment]
Hi! Thanks for reporting this, the new update fix it :D
