### ISSUE TITLE
Support 1.18.2

### ISSUE THREAD

**Issue by mani1232** [divios/DailyShop#122]
add support 1.18.2
[07:34:34 WARN]: [DailyShop] Task #921 for DailyShop v3.7 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class io.github.divios.dependencies.nbt.nbtapi.NBTReflectionUtil
        at io.github.divios.dependencies.nbt.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.dItem.getItemWithId(dItem.java:207) ~[DailyShop-3.7.jar:?]
        at io.github.divios.dailyShop.lorestategy.shopItemsLore.applyLore(shopItemsLore.java:27) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.buttons.DailyItemFactory$DailyItemButton.getItem(DailyItemFactory.java:45) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.buttons.Button.getItem(Button.java:11) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.gui.ButtonGui.setButton(ButtonGui.java:78) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.gui.MultiButtonGui.setButton(MultiButtonGui.java:47) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.ShopView.setDailyItem(ShopView.java:128) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.ShopView.setDailyItems(ShopView.java:102) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.dShop.reStock(dShop.java:261) ~[DailyShop-3.7.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1562) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1248) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:34:34 WARN]: [DailyShop] Task #922 for DailyShop v3.7 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class io.github.divios.dependencies.nbt.nbtapi.NBTReflectionUtil
        at io.github.divios.dependencies.nbt.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.dItem.getItemWithId(dItem.java:207) ~[DailyShop-3.7.jar:?]
        at io.github.divios.dailyShop.lorestategy.shopItemsLore.applyLore(shopItemsLore.java:27) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.buttons.DailyItemFactory$DailyItemButton.getItem(DailyItemFactory.java:45) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.buttons.Button.getItem(Button.java:11) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.gui.ButtonGui.setButton(ButtonGui.java:78) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.gui.MultiButtonGui.setButton(MultiButtonGui.java:47) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.ShopView.setDailyItem(ShopView.java:128) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.ShopView.setDailyItems(ShopView.java:102) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.dShop.reStock(dShop.java:261) ~[DailyShop-3.7.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1562) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1248) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:34:34 WARN]: [DailyShop] Task #923 for DailyShop v3.7 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class io.github.divios.dependencies.nbt.nbtapi.NBTReflectionUtil
        at io.github.divios.dependencies.nbt.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.dItem.getItemWithId(dItem.java:207) ~[DailyShop-3.7.jar:?]
        at io.github.divios.dailyShop.lorestategy.shopItemsLore.applyLore(shopItemsLore.java:27) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.buttons.DailyItemFactory$DailyItemButton.getItem(DailyItemFactory.java:45) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.buttons.Button.getItem(Button.java:11) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.gui.ButtonGui.setButton(ButtonGui.java:78) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.gui.MultiButtonGui.setButton(MultiButtonGui.java:47) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.ShopView.setDailyItem(ShopView.java:128) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.view.ShopView.setDailyItems(ShopView.java:102) ~[DailyShop-3.7.jar:?]
        at io.github.divios.lib.dLib.shop.dShop.reStock(dShop.java:261) ~[DailyShop-3.7.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1562) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1248) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1579]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:34:34 ERROR]: [DailyShop] An error occurred executing an SQLite query: Method not loaded! 'ITEMSTACK_NMSCOPY'
[07:34:34 WARN]: io.github.divios.dependencies.nbt.nbtapi.NbtApiException: Method not loaded! 'ITEMSTACK_NMSCOPY'
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.dependencies.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:176)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.dependencies.nbt.nbtapi.NBTItem.convertItemtoNBT(NBTItem.java:154)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.dItem.toJson(dItem.java:514)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.shop.view.ShopViewFactory.lambda$static$0(ShopViewFactory.java:25)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:74)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[07:34:34 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
[07:34:34 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
[07:34:34 WARN]:        at com.google.gson.Gson.toJson(Gson.java:735)
[07:34:34 WARN]:        at com.google.gson.Gson.toJsonTree(Gson.java:628)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.shop.view.ShopViewFactory.toJson(ShopViewFactory.java:74)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.lambda$updateGui$19(databaseManager.java:260)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.updateGui(databaseManager.java:256)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.lambda$updateGuiAsync$20(databaseManager.java:268)
[07:34:34 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[07:34:34 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:34:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:34:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:34:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:34:34 ERROR]: [DailyShop] An error occurred executing an SQLite query: Method not loaded! 'ITEMSTACK_NMSCOPY'
[07:34:34 WARN]: io.github.divios.dependencies.nbt.nbtapi.NbtApiException: Method not loaded! 'ITEMSTACK_NMSCOPY'
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.dependencies.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:176)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.dependencies.nbt.nbtapi.NBTItem.convertItemtoNBT(NBTItem.java:154)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.dItem.toJson(dItem.java:514)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.shop.view.ShopViewFactory.lambda$static$0(ShopViewFactory.java:25)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:74)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[07:34:34 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
[07:34:34 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
[07:34:34 WARN]:        at com.google.gson.Gson.toJson(Gson.java:735)
[07:34:34 WARN]:        at com.google.gson.Gson.toJsonTree(Gson.java:628)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.shop.view.ShopViewFactory.toJson(ShopViewFactory.java:74)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.lambda$updateGui$19(databaseManager.java:260)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.updateGui(databaseManager.java:256)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.lambda$updateGuiAsync$20(databaseManager.java:268)
[07:34:34 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[07:34:34 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:34:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:34:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:34:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:34:34 ERROR]: [DailyShop] An error occurred executing an SQLite query: Method not loaded! 'ITEMSTACK_NMSCOPY'
[07:34:34 WARN]: io.github.divios.dependencies.nbt.nbtapi.NbtApiException: Method not loaded! 'ITEMSTACK_NMSCOPY'
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.dependencies.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:176)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.dependencies.nbt.nbtapi.NBTItem.convertItemtoNBT(NBTItem.java:154)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.dItem.toJson(dItem.java:514)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.shop.view.ShopViewFactory.lambda$static$0(ShopViewFactory.java:25)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:74)
[07:34:34 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[07:34:34 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
[07:34:34 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
[07:34:34 WARN]:        at com.google.gson.Gson.toJson(Gson.java:735)
[07:34:34 WARN]:        at com.google.gson.Gson.toJsonTree(Gson.java:628)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.dLib.shop.view.ShopViewFactory.toJson(ShopViewFactory.java:74)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.lambda$updateGui$19(databaseManager.java:260)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.updateGui(databaseManager.java:256)
[07:34:34 WARN]:        at DailyShop-3.7.jar//io.github.divios.lib.storage.databaseManager.lambda$updateGuiAsync$20(databaseManager.java:268)
[07:34:34 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[07:34:34 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:34:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:34:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:34:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by divios** [comment]
Hi! I didn't  notice that they changed again reflections... I just updated the dependencies and [this build works](https://we.tl/t-r838nGayd3). Before I update it to spigot, could you try it and confirm everything woks?

**Comment by mani1232** [comment]
> Hi! I didn't notice that they changed reflections again... I just updated the dependencies and [this build works](https://we.tl/t-r838nGayd3). Before I update it to spigot, could you try it and confirm everything woks?

Working
