### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#131]
Hi, as you know I got hung up on old versions of the plugin for many reasons and today when I updated the plugin file - it stopped working (just no products in stores)

by the way i replied, sorry i was very busy + forgot: https://github.com/divios/DailyShop/issues/119#issuecomment-1073077351

[02:44:56 INFO]: _yellow_pillow_ issued server command: /rdshop restock
[02:44:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rdshop' in plugin DailyShop v3.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2279) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2090) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2072) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:48) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[app:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:124) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1441) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1434) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1409) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1319) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at io.github.divios.jcommands.JCommandListener.wrapArgs(JCommandListener.java:84) ~[DailyShop-3.7.jar:?]
        at io.github.divios.jcommands.JCommandListener.onCommand(JCommandListener.java:68) ~[DailyShop-3.7.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[ssspigot23397481914533840136.jar:SSSpigot2-1.17.1-20220215-dd3d08b]
        ... 18 more

**Comment by divios** [comment]
Hi! This error has already been reported, here the link #92. Note that the commands should be runned like /ds restock {shop}/all
