### ISSUE TITLE
Trouble making an API

### ISSUE THREAD

**Issue by Utorque** [divios/DailyShop#136]
Hi,
before saying anything, I'm a noob at making java plugin. Still, there is something weird I don't understand and can't find a solution on the internet.
For now I have almost nothing on my api : litterally only the example you gave [here](https://diviosx.gitbook.io/daily-random-shop/developers/api), i.e. this :

    @Override
    public void onEnable() {
    
        DailyShop api = DailyShop.getInstance();
        shopsManager manager = api.getShopsManager();
    
    }

On build and compile, the packages are successfully imported. However, it crashes on load and makes the DailyShop plugin crash with it.

Crash on the API :
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "plugin" is null
	at io.github.divios.dependencies.Core_lib.database.SQLiteConnector.<init>(SQLiteConnector.java:20) ~[DailyShop-3.7.jar:?]
	at io.github.divios.lib.storage.dataManager.getInstance(dataManager.java:37) ~[DailyShop-3.7.jar:?]
	at io.github.divios.lib.managers.shopsManager.getInstance(shopsManager.java:27) ~[DailyShop-3.7.jar:?]
	at io.github.divios.dailyShop.DailyShop.getShopsManager(DailyShop.java:81) ~[DailyShop-3.7.jar:?]
	at test.test.dailyshopToDiscordAPI.onEnable(dailyshopToDiscordAPI.java:23) ~[test-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-278]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-278]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

crash on the DailyShop plugin :
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDataFolder()" because "plugin" is null
	at io.github.divios.dependencies.Core_lib.database.SQLiteConnector.<init>(SQLiteConnector.java:20) ~[DailyShop-3.7.jar:?]
	at io.github.divios.lib.storage.dataManager.getInstance(dataManager.java:37) ~[DailyShop-3.7.jar:?]
	at io.github.divios.dailyShop.DailyShop.onEnable(DailyShop.java:48) ~[DailyShop-3.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-278]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-278]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Any idea on how to avoid that ?

**Comment by Utorque** [comment]
It was just a question of messed up dependency.

**Comment by divios** [comment]
Hi! Sorry for the late reply. Did you achieve what you wanted to do? My take is that you are not setting the dailyshop dependency on the plugin.yml file
