### ISSUE TITLE
AN internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by SnowyB1** [divios/DailyShop#137]
the commands for the shop are not working correctly see below for 1.12.2

12.04 20:48:51 [Server] INFO birz01 issued server command: /ds
12.04 20:48:57 [Server] INFO birz01 issued server command: /dsshop reload
12.04 20:49:03 [Server] INFO birz01 issued server command: /rdshop reload
12.04 20:49:03 [Server] INFO Reading lang.yml...
12.04 20:49:03 [Server] INFO No changes were made on lang.yml, skipping...
12.04 20:49:03 [Server] INFO Reading settings.yml... 
12.04 20:49:03 [Server] INFO No changes were made in settings.yml, skipping...
12.04 20:49:03 [Server] ERROR null
12.04 20:49:03 [Server] INFO  org.bukkit.command.CommandException: Unhandled exception executing command 'rdshop' in plugin DailyShop v3.8
12.04 20:49:03 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
12.04 20:49:03 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[SimpleCommandMap.class:?]
12.04 20:49:03 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1590) ~[pa.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1429) ~[pa.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
12.04 20:49:03 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
12.04 20:49:03 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
12.04 20:49:03 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
12.04 20:49:03 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
12.04 20:49:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
12.04 20:49:03 [Server] INFO Caused by: java.lang.NullPointerException
12.04 20:49:03 [Server] INFO at io.github.divios.dailyShop.files.resourceManager.reload(resourceManager.java:43) ~[?:?]
12.04 20:49:03 [Server] INFO at io.github.divios.dailyShop.DailyShop.reload(DailyShop.java:101) ~[?:?]
12.04 20:49:03 [Server] INFO at io.github.divios.dailyShop.commands.reloadCommand.lambda$getCommand$0(reloadCommand.java:16) ~[?:?]
12.04 20:49:03 [Server] INFO at io.github.divios.jcommands.JCommand.lambda$new$2(JCommand.java:30) ~[?:?]
12.04 20:49:03 [Server] INFO at io.github.divios.jcommands.JCommandListener.onCommand(JCommandListener.java:68) ~[?:?]
12.04 20:49:03 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
12.04 20:49:03 [Server] INFO ... 15 more
12.04 20:49:05 [Server] INFO CONSOLE issued server command: /list 
12.04 20:49:05 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:49:05 [Server] INFO Admins: [Owner]birz01
12.04 20:49:56 [Server] INFO CONSOLE issued server command: /list 
12.04 20:49:56 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:49:56 [Server] INFO Admins: [Owner]birz01
12.04 20:50:24 [Server] INFO birz01 issued server command: /rdshop open ore
12.04 20:50:25 [Server] INFO birz01 issued server command: /rdshop open ores
12.04 20:50:33 [Server] INFO birz01 issued server command: /rdshop open ores birz01
12.04 20:50:36 [Server] INFO birz01 issued server command: /rdshop open ore birz01
12.04 20:50:40 [Server] INFO Useless Pokémon will be wiped away in 5m!
12.04 20:50:48 [Server] INFO CONSOLE issued server command: /list 
12.04 20:50:48 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:50:48 [Server] INFO Admins: [Owner]birz01
12.04 20:51:40 [Server] INFO CONSOLE issued server command: /list 
12.04 20:51:40 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:51:40 [Server] INFO Admins: [Owner]birz01
12.04 20:52:22 [Server] INFO birz01 issued server command: /rdshop manager
12.04 20:52:31 [Server] INFO CONSOLE issued server command: /list 
12.04 20:52:31 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:52:31 [Server] INFO Admins: [Owner]birz01
12.04 20:52:35 [Server] INFO birz01 issued server command: /shop
12.04 20:52:37 [Server] INFO birz01 issued server command: /rdshop manager
12.04 20:52:45 [Server] WARN Task #9689 for DailyShop v3.8 generated an exception
12.04 20:52:45 [Server] INFO  java.lang.NoSuchMethodError: net.md_5.bungee.api.ChatColor.of(Ljava/awt/Color;)Lnet/md_5/bungee/api/ChatColor;
12.04 20:52:45 [Server] INFO at io.github.divios.jtext.parsers.gradientColorParser.rgbGradient(gradientColorParser.java:64) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.jtext.parsers.gradientColorParser.parse(gradientColorParser.java:27) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.jtext.JTextBuilder.parse(JTextBuilder.java:188) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.jtext.JTextBuilder.parse(JTextBuilder.java:160) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.dailyShop.files.Messages.broadcast(Messages.java:70) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.lib.dLib.shop.dShop.reStock(dShop.java:268) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.lib.managers.WrappedShop.reStock(WrappedShop.java:148) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.lib.managers.shopsManager.createShop(shopsManager.java:74) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.dailyShop.guis.settings.shopsManagerGui.lambda$nonContentAction$17(shopsManagerGui.java:222) ~[?:?]
12.04 20:52:45 [Server] INFO at io.github.divios.core_lib.misc.ChatPrompt$1.lambda$acceptInput$0(ChatPrompt.java:100) ~[?:?]
12.04 20:52:45 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[CraftTask.class:?]
12.04 20:52:45 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:?]
12.04 20:52:45 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) [MinecraftServer.class:?]
12.04 20:52:45 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
12.04 20:52:45 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
12.04 20:52:45 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
12.04 20:52:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
12.04 20:53:10 [Server] INFO Useless Pokémon will be wiped away in 2m30s!
12.04 20:53:23 [Server] INFO CONSOLE issued server command: /list 
12.04 20:53:23 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:53:23 [Server] INFO Admins: [Owner]birz01
12.04 20:54:15 [Server] INFO CONSOLE issued server command: /list 
12.04 20:54:15 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:54:15 [Server] INFO Admins: [Owner]birz01
12.04 20:54:25 [Server] INFO Useless Pokémon will be wiped away in 1m15s!
12.04 20:54:50 [Server] INFO Useless Pokémon will be wiped away in 50s!
12.04 20:54:54 [Multicraft] Auto-saving world...
12.04 20:54:54 [Server] INFO Saving is already turned on
12.04 20:54:54 [Server] INFO Saving...
12.04 20:54:54 [Server] INFO World saved.
12.04 20:55:06 [Server] INFO CONSOLE issued server command: /list 
12.04 20:55:06 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:55:06 [Server] INFO Admins: [Owner]birz01
12.04 20:55:15 [Server] INFO Useless Pokémon will be wiped away in 25s!
12.04 20:55:58 [Server] INFO CONSOLE issued server command: /list 
12.04 20:55:58 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:55:58 [Server] INFO Admins: [Owner]birz01
12.04 20:56:50 [Server] INFO CONSOLE issued server command: /list 
12.04 20:56:50 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:56:50 [Server] INFO Admins: [Owner]birz01
12.04 20:57:41 [Server] INFO CONSOLE issued server command: /list 
12.04 20:57:41 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:57:41 [Server] INFO Admins: [Owner]birz01
12.04 20:58:33 [Server] INFO CONSOLE issued server command: /list 
12.04 20:58:33 [Server] INFO There are 1 out of maximum 200 players online.
12.04 20:58:33 [Server] INFO Admins: [AFK][Owner]birz01

**Comment by SnowyB1** [comment]
this happens with several of the commands some dont even work, am i missing something?
