### ISSUE TITLE
 java.lang.IllegalStateException: Unable to deserialize item.

### ISSUE THREAD

**Issue by Chlachta** [divios/DailyShop#140]
Hello, 
We using paid DailyShop and we got some errors with itemsadder items in shop right now - when I created some itemsadder things to buy, it worked, but after recently update ( to 3.8 and high) we got this error in console and items disappear from config file and shop. 
Server version: 1.18.1, 1.18.2 (from today), latest paper, java 17, DailyShop version 3.8A, itemsadder for custom items :)

[12:40:44 ERROR]: [DailyShop] An error occurred executing an SQLite query: Unable to deserialize item.
[12:40:44 WARN]: java.lang.IllegalStateException: Unable to deserialize item.
[12:40:44 WARN]:        at DailyShop-3.8.jar//io.github.divios.core_lib.itemutils.ItemUtils.deserialize(ItemUtils.java:850)
[12:40:44 WARN]:        at DailyShop-3.8.jar//io.github.divios.lib.storage.databaseManager.lambda$getLogEntries$30(databaseManager.java:371)
[12:40:44 WARN]:        at DailyShop-3.8.jar//io.github.divios.core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:56)
[12:40:44 WARN]:        at DailyShop-3.8.jar//io.github.divios.lib.storage.databaseManager.getLogEntries(databaseManager.java:350)
[12:40:44 WARN]:        at DailyShop-3.8.jar//io.github.divios.lib.storage.databaseManager.dropOldLogEntries(databaseManager.java:405)
[12:40:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:40:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:40:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:40:44 WARN]: Caused by: java.io.IOException: Failed to deserialize object
[12:40:44 WARN]:        at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:59)
[12:40:44 WARN]:        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:51)
[12:40:44 WARN]:        at java.base/java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1795)
[12:40:44 WARN]:        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
[12:40:44 WARN]:        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
[12:40:44 WARN]:        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
[12:40:44 WARN]:        at DailyShop-3.8.jar//io.github.divios.core_lib.itemutils.ItemUtils.deserialize(ItemUtils.java:844)
[12:40:44 WARN]:        ... 7 more
[12:40:44 WARN]: Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('dev.lone.itemsadder.main.bo')
[12:40:44 WARN]:        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197)
[12:40:44 WARN]:        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49)

**Comment by divios** [comment]
Hi! Thanks for reporting it. I will take a look at the dependencies, maybe a changed something, but it seems it is not detecting the itemsAdder api

**Comment by divios** [comment]
Hi! This was fixed on the last update
