### ISSUE TITLE
3.9 Start Error

### ISSUE THREAD

**Issue by 849025143** [divios/DailyShop#152]
[18:49:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ds' in plugin DailyShop v3.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-35187d3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-35187d3]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:712) ~[CraftServer.class:git-CatServer-1.12.2-35187d3]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1659) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1460) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_271]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_271]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
        at io.github.divios.dailyShop.lorestategy.shopsManagerLore.applyLore(shopsManagerLore.java:28) ~[?:?]
        at io.github.divios.dailyShop.guis.settings.shopsManagerGui.lambda$createInvs$0(shopsManagerGui.java:80) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_271]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.AbstractTask.compute(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_271]
        at io.github.divios.core_lib.inventory.builder.paginatedGuiBuilder.lambda$withItems$0(paginatedGuiBuilder.java:26) ~[?:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui.init(paginatedGui.java:83) ~[?:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui.<init>(paginatedGui.java:53) ~[?:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui.<init>(paginatedGui.java:24) ~[?:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui$BuilderImpl.build(paginatedGui.java:228) ~[?:?]
        at io.github.divios.dailyShop.guis.settings.shopsManagerGui.createInvs(shopsManagerGui.java:116) ~[?:?]
        at io.github.divios.dailyShop.guis.settings.shopsManagerGui.<init>(shopsManagerGui.java:45) ~[?:?]
        at io.github.divios.dailyShop.guis.settings.shopsManagerGui.open(shopsManagerGui.java:50) ~[?:?]
        at io.github.divios.dailyShop.commands.managerCommand.lambda$getCommand$0(managerCommand.java:13) ~[?:?]
        at io.github.divios.jcommands.JCommandListener.onCommand(JCommandListener.java:70) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-35187d3]
        ... 15 more

**Comment by divios** [comment]
Hi! In what minecraft version are you using the plugin?

**Comment by 849025143** [comment]
In the above information, you can see that my version is 1.12.2.

**Comment by divios** [comment]
Ah you are right. This seems to be an error that only happens on versions <1.12, I will check it this afternoon

**Comment by divios** [comment]
Hi again! Sorry for the delay, this [build fix](https://we.tl/t-MLOZNxERMZ) it
