### ISSUE TITLE
sell items mmoitems with random stats

### ISSUE THREAD

**Issue by Weyl1** [divios/DailyShop#159]
My items of mmoitems have random values, the worry is that because of that I can not sell the item to par if I fall on the same value.

I would like to be able to sell a mmoitems object with random stats

It would be to remove the random stats but I can't consider

![one3](https://user-images.githubusercontent.com/96068728/176349282-855bfd1f-ec44-432d-88f3-398ecb2a4dd0.PNG)
![one2](https://user-images.githubusercontent.com/96068728/176349284-e15dba82-3433-4e2b-9d8c-48543916b042.PNG)
![one4](https://user-images.githubusercontent.com/96068728/176349286-b7b89952-1de4-49fb-9176-15a1e59c41eb.PNG)

**Comment by divios** [comment]
Hi!

This was supported in the earlier versions of the plug-in, but due to some refactoring and bad decisions a decided to removed it since it was throwing tons of errors

I will try to implement it now, hopefully with the years of experience I have now I can make it right

**Comment by divios** [comment]
Hi again!

Please try [this build](https://we.tl/t-PyKQrwTvVg) and let me know if it works as expected. I myself don't have MMOItems so I cannot properly test it, but it should work

**Comment by Weyl1** [comment]
> Please try [this build](https://we.tl/t-PyKQrwTvVg) and let me know if it works as expected. I myself don't have MMOItems so I cannot properly test it, but it should work

**Comment by Weyl1** [comment]
No it makes me the same problem, I can not sell an item with different stats

**Comment by divios** [comment]
Okay, I found what was missing, [this build](https://we.tl/t-a4LOO3www8) should work

**Comment by Weyl1** [comment]
Ok it works and I'm no problem in the console

**Comment by divios** [comment]
Great, thanks for the feedback. I will close the ticket then.

**Comment by Weyl1** [comment]
sorry for the inconvenience but the command ds sell (all/gui/hand) the same problem

**Comment by divios** [comment]
Ahh dammit I completely forgot, I will fix as soon as I can

**Comment by divios** [comment]
Alright [this one](https://we.tl/t-RXgoTok207) should work.

**Comment by Weyl1** [comment]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.getId(OraxenUtils.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.getId(OraxenUtils.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.getId(OraxenUtils.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.getId(OraxenUtils.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.getId(OraxenUtils.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.getId(OraxenUtils.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.getId(OraxenUtils.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.dailyShop.utils.OraxenUtils.isOraxenItem(OraxenUtils.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.confirmMenu.comparators.OraxenComparator.matches(OraxenComparator.java:12) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.confirmMenu.comparators.ComparatorFactory.lambda$match$0(ComparatorFactory.java:23) ~[DailyShop-3.9.1.jar:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:540) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:526) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512) ~[?:?]
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[?:?]
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
at io.github.divios.lib.dLib.confirmMenu.comparators.ComparatorFactory.match(ComparatorFactory.java:24) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.cashregister.preconditions.CountItemPrecondition.validate(CountItemPrecondition.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.cashregister.MultiplePreconditions.SellPreconditions.lambda$validate$0(SellPreconditions.java:28) ~[DailyShop-3.9.1.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at io.github.divios.lib.dLib.shop.cashregister.MultiplePreconditions.SellPreconditions.validate(SellPreconditions.java:28) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.cashregister.carts.SellCart.addToCart(SellCart.java:26) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.cashregister.carts.Cart.<init>(Cart.java:25) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.cashregister.carts.SellCart.<init>(SellCart.java:21) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.cashregister.CashRegister.initialize(CashRegister.java:36) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.cashregister.CashRegister.onItemClick(CashRegister.java:50) ~[DailyShop-3.9.1.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at io.github.divios.core_lib.events.Events.callEvent(Events.java:16) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.view.buttons.DailyItemFactory$DailyItemButton.execute(DailyItemFactory.java:42) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.lib.dLib.shop.view.gui.ButtonGui.lambda$createClickListener$2(ButtonGui.java:59) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.core_lib.events.Events$EventSubscriptionBuilder.lambda$handler$0(Events.java:53) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.core_lib.events.SingleSubscription.handleEvent(SingleSubscription.java:37) ~[DailyShop-3.9.1.jar:?]
at io.github.divios.core_lib.events.SingleSubscription.lambda$initialize$0(SingleSubscription.java:32) ~[DailyShop-3.9.1.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2861) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-386]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-386]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-386]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-386]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-386]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-386]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-386]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
at java.lang.Thread.run(Thread.java:889) ~[?:?]

**Comment by divios** [comment]
I messes up in a condition... try [this build](https://we.tl/t-kpWGRg038Y) and let me know if everything work as expected.
