### ISSUE TITLE
daily shop logs not working 

### ISSUE THREAD

**Issue by seanm-cloud** [divios/DailyShop#167]
When entering the command **/daily shop log**  an internal error occurs. 

```
org.bukkit.command.CommandException: Unhandled exception executing command 'dailyshop' in plugin DailyShop v3.9.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:923) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:57) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1439) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:178) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1417) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1410) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1388) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1299) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:312) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot format given Object as a Date
        at io.github.divios.dailyShop.utils.Exceptions.tryTo(Exceptions.java:34) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.dailyShop.utils.Exceptions.tryTo(Exceptions.java:9) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.init(RecordBookGui.java:162) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.<init>(RecordBookGui.java:37) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.<init>(RecordBookGui.java:25) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui$LogGuiBuilder.prompt(RecordBookGui.java:199) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.dailyShop.commands.loggerCommand.lambda$getCommand$0(loggerCommand.java:16) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.jcommands.JCommandListener.onCommand(JCommandListener.java:70) ~[DailyShop-3.9.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        ... 21 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot format given Object as a Date
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.lambda$init$13(RecordBookGui.java:162) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.dailyShop.utils.Exceptions.lambda$tryTo$0(Exceptions.java:10) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.dailyShop.utils.Exceptions.tryTo(Exceptions.java:32) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.dailyShop.utils.Exceptions.tryTo(Exceptions.java:9) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.init(RecordBookGui.java:162) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.<init>(RecordBookGui.java:37) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.<init>(RecordBookGui.java:25) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui$LogGuiBuilder.prompt(RecordBookGui.java:199) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.dailyShop.commands.loggerCommand.lambda$getCommand$0(loggerCommand.java:16) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.jcommands.JCommandListener.onCommand(JCommandListener.java:70) ~[DailyShop-3.9.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        ... 21 more
Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Date
        at java.text.DateFormat.format(DateFormat.java:342) ~[?:?]
        at java.text.Format.format(Format.java:159) ~[?:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.lambda$init$3(RecordBookGui.java:66) ~[DailyShop-3.9.1.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayDeque$DeqSpliterator.forEachRemaining(ArrayDeque.java:848) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at io.github.divios.lib.dLib.registry.RecordBookGui.lambda$init$4(RecordBookGui.java:72) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui.init(paginatedGui.java:87) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui.<init>(paginatedGui.java:57) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui.<init>(paginatedGui.java:28) ~[DailyShop-3.9.1.jar:?]
        at io.github.divios.core_lib.inventory.builder.paginatedGui$BuilderImpl.build(paginatedGui.java:235) ~[DailyShop-3.9.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by Akiranya** [comment]
Have you tried deleting the data file of DailyShop?
