### ISSUE TITLE
We cannot add modded items ! seriously....

### ISSUE THREAD

**Issue by Kao2705** [divios/DailyShop#178]
[16:11:37 INFO]: Ouisky issued server command: /ds restock drops
[16:11:37 INFO]: [DailyShop] DailyShop > Renovated items of shop drops
[16:11:40 INFO]: [DailyShop] There was a problem saving the shop drops
[16:11:40 WARN]: java.lang.IllegalArgumentException: Unsupported material from item: PIXELMON_POKE_BALL (0)
[16:11:40 WARN]:        at io.github.divios.dependencies.XSeries.XMaterial.matchXMaterial(XMaterial.java:1774)
[16:11:40 WARN]:        at io.github.divios.lib.serialize.wrappers.WrappedMaterial.getMaterial(WrappedMaterial.java:27)
[16:11:40 WARN]:        at io.github.divios.lib.serialize.adapters.dItemAdapter.serialize(dItemAdapter.java:64)
[16:11:40 WARN]:        at io.github.divios.lib.serialize.adapters.dItemAdapter.serialize(dItemAdapter.java:31)
[16:11:40 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[16:11:40 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[16:11:40 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
[16:11:40 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
[16:11:40 WARN]:        at com.google.gson.Gson.toJson(Gson.java:669)
[16:11:40 WARN]:        at com.google.gson.Gson.toJsonTree(Gson.java:562)
[16:11:40 WARN]:        at com.google.gson.Gson.toJsonTree(Gson.java:541)
[16:11:40 WARN]:        at io.github.divios.lib.serialize.adapters.dShopStateAdapter.serialize(dShopStateAdapter.java:115)
[16:11:40 WARN]:        at io.github.divios.lib.serialize.serializerApi.saveShopToFile(serializerApi.java:53)
[16:11:40 WARN]:        at io.github.divios.lib.serialize.serializerApi.lambda$saveShopToFileAsync$2(serializerApi.java:65)
[16:11:40 WARN]:        at io.github.divios.lib.serialize.serializerApi.lambda$static$1(serializerApi.java:40)
[16:11:40 WARN]:        at io.github.divios.dailyShop.utils.cache.decorators.CacheRemoveListener.invalidate(CacheRemoveListener.java:43)
[16:11:40 WARN]:        at io.github.divios.dailyShop.utils.cache.decorators.CacheRemoveTask.invalidate(CacheRemoveTask.java:59)
[16:11:40 WARN]:        at io.github.divios.dailyShop.utils.cache.decorators.CacheRemoveTask.lambda$startTask$0(CacheRemoveTask.java:35)
[16:11:40 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:98)
[16:11:40 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:462)
[16:11:40 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1056)
[16:11:40 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338)
[16:11:40 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1002)
[16:11:40 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:817)
[16:11:40 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268)
[16:11:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by refractored** [comment]
Well what do you expect? Spigot and Forge are vastly different APIs. Trying to tie them together is going to have issues arrise.
