### ISSUE TITLE
CommandException "null" when executing "ds open <shop>" (v3.4.8)

### ISSUE THREAD

**Issue by marcjoancr** [divios/DailyShop#20]
When executing command `ds open <shop>`.
```
[ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'ds' in plugin DailyShop v3.4.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:1847) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at com.denizenscript.denizen.nms.v1_17.impl.network.handlers.AbstractListenerPlayInImpl.chat(AbstractListenerPlayInImpl.java:91) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.chat(CraftPlayer.java:359) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
at net.citizensnpcs.trait.CommandTrait$NPCCommand.run(CommandTrait.java:439) ~[?:?]
at net.citizensnpcs.trait.CommandTrait$1$3.run(CommandTrait.java:248) ~[?:?]
at net.citizensnpcs.trait.CommandTrait$1.runCommand(CommandTrait.java:253) ~[?:?]
at net.citizensnpcs.trait.CommandTrait$1.run(CommandTrait.java:219) ~[?:?]
at net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:260) ~[?:?]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:498) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor646.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
```
[...]
```
Caused by: java.lang.NoClassDefFoundError: io/github/divios/lib/dLib/synchronizedGui/taskPool/updatePool
at io.github.divios.lib.dLib.synchronizedGui.singleGui.singleGuiImpl.<init>(singleGuiImpl.java:52) ~[?:?]
at io.github.divios.lib.dLib.synchronizedGui.singleGui.singleGuiImpl.<init>(singleGuiImpl.java:42) ~[?:?]
at io.github.divios.lib.dLib.synchronizedGui.singleGui.singleGui.create(singleGui.java:21) ~[?:?]
at io.github.divios.lib.dLib.synchronizedGui.abstractSyncMenu.generate(abstractSyncMenu.java:116) ~[?:?]
at io.github.divios.lib.dLib.dShop.openShop(dShop.java:96) ~[?:?]
at io.github.divios.dailyShop.commands.open.run(open.java:90) ~[?:?]
at io.github.divios.dailyShop.shaded.Core_lib.commands.CommandManager.lambda$onCommand$1(CommandManager.java:87) ~[?:?]
at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
at io.github.divios.dailyShop.shaded.Core_lib.commands.CommandManager.onCommand(CommandManager.java:69) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
```

**Comment by divios** [comment]
Very rare bug... Have to check it before updating resource but has something to with gradle doing something fun on runTime
