### ISSUE TITLE
when player join to server eror Amount must be greater than 0

### ISSUE THREAD

**Issue by l3unnyAnoF4** [divios/DailyShop#28]
```
[20:12:52 WARN]: java.lang.IllegalArgumentException: Amount must be greater than 0
[20:12:52 WARN]:        at DailyShop-3.5.1 (1).jar//io.github.divios.dailyShop.shaded.Core_lib.itemutils.ItemUtils.give(ItemUtils.java:585)
[20:12:52 WARN]:        at DailyShop-3.5.1 (1).jar//io.github.divios.dailyShop.guis.abstractConfirmGui$cacheEntry.restore(abstractConfirmGui.java:295)
[20:12:52 WARN]:        at DailyShop-3.5.1 (1).jar//io.github.divios.dailyShop.guis.abstractConfirmGui.lambda$static$2(abstractConfirmGui.java:94)
[20:12:52 WARN]:        at DailyShop-3.5.1 (1).jar//io.github.divios.dailyShop.shaded.Core_lib.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:120)
[20:12:52 WARN]:        at DailyShop-3.5.1 (1).jar//io.github.divios.dailyShop.shaded.Core_lib.event.functional.single.HelperEventListener.execute(HelperEventListener.java:134)
[20:12:52 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:12:52 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:12:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[20:12:52 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:360)
[20:12:52 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302)
[20:12:52 WARN]:        at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:308)
[20:12:52 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:555)
[20:12:52 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[20:12:52 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1706)
[20:12:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:501)
[20:12:52 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1524)
[20:12:52 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[20:12:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:12:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by l3unnyAnoF4** [comment]
![image](https://user-images.githubusercontent.com/67956962/133890556-28107715-cc79-4821-8a8e-906f4c815483.png)

**Comment by divios** [comment]
Oh you are right, I know where that error comes, I’ll fix it ASAP

**Comment by divios** [comment]
Fixed on the new update
