### ISSUE TITLE
Error occurred while enabling DailyShop v3.5.3

### ISSUE THREAD

**Issue by l3unnyAnoF4** [divios/DailyShop#36]
### I run the server and get the message

```
[23:36:17 ERROR]: Error occurred while enabling DailyShop v3.5.3 (Is it up to date?)
[23:36:17 ERROR]: Suspected Plugins:
[23:36:17 ERROR]:       DailyShop{enabled,ver=3.5.3,path=plugins\DailyShop-3.5.3.jar}
[23:36:17 ERROR]: Exception details below:
java.lang.NoClassDefFoundError: net/Indyuce/mmoitems/api/event/ItemDropEvent
        at io.github.divios.lib.dLib.confirmMenu.buyConfirmMenu.createDropItemListener(buyConfirmMenu.java:51) ~[DailyShop-3.5.3.jar:?]
        at io.github.divios.lib.dLib.confirmMenu.buyConfirmMenu.<clinit>(buyConfirmMenu.java:35) ~[DailyShop-3.5.3.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at io.github.divios.dailyShop.DailyShop.onEnable(DailyShop.java:50) ~[DailyShop-3.5.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:741) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:328) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1234) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.Indyuce.mmoitems.api.event.ItemDropEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[ssspigot22125084939180764926.jar:SSSpigot2-1.17.1-20210926-24f062c]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 15 more
[23:36:17 INFO]: [DailyShop] Disabling DailyShop v3.5.3
[23:36:17 INFO]: [CMILib] Enabling CMILib v1.0.3.7
[23:36:17 WARN]: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: de/tr7zw/nbtapi/utils/nmsmappings/ReflectionMethod$Since
[23:36:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[23:36:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.dailyShop.utils.FutureUtils.waitFor(FutureUtils.java:10)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.storage.dataManager.lambda$getShops$1(dataManager.java:60)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.dailyShop.shaded.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.storage.dataManager.lambda$getShops$2(dataManager.java:48)
[23:36:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[23:36:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[23:36:17 WARN]: Caused by: java.lang.NoClassDefFoundError: de/tr7zw/nbtapi/utils/nmsmappings/ReflectionMethod$Since
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:22)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//de.tr7zw.nbtapi.NBTContainer.<init>(NBTContainer.java:66)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.dLib.dItem.fromJson(dItem.java:724)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.dLib.dItem.fromBase64(dItem.java:720)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.storage.dataManager.lambda$getShop$3(dataManager.java:82)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.dailyShop.shaded.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.storage.dataManager.lambda$getShop$4(dataManager.java:76)
[23:36:17 WARN]:        ... 7 more
[23:36:17 WARN]: Exception in thread "Thread-6" java.lang.NoClassDefFoundError: de/tr7zw/nbtapi/utils/VersionChecker
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//de.tr7zw.nbtapi.utils.MinecraftVersion.lambda$init$0(MinecraftVersion.java:105)
[23:36:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[23:36:17 ERROR]: [DailyShop] An error occurred executing an SQLite query: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because "<parameter6>" is null
[23:36:17 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because "<parameter6>" is null
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.dLib.dShop.<init>(dShop.java:68)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.storage.dataManager.lambda$getShops$1(dataManager.java:60)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.dailyShop.shaded.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[23:36:17 WARN]:        at DailyShop-3.5.3.jar//io.github.divios.lib.storage.dataManager.lambda$getShops$2(dataManager.java:48)
[23:36:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[23:36:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[23:36:17 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by divios** [comment]
I just realized that i imported the wrong method, from MMOitems instead of bukkit, uploading the fix right now
