### ISSUE TITLE
[BUG] Plugin disband

### ISSUE THREAD

**Issue by 849025143** [divios/DailyShop#47]
Server: paper-1.16.5
plugin: 3.5.8

[18:26:46 INFO]: [DailyShop] Hooked to PlaceholderAPI
[18:26:46 ERROR]: Error occurred while enabling DailyShop v3.5.8 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.black_ixx.playerpoints.PlayerPoints org.black_ixx.playerpoints.PlayerPoints.getInstance()'
        at io.github.divios.dailyShop.hooks.playerPointsHook.hook(playerPointsHook.java:13) ~[?:?]
        at io.github.divios.dailyShop.hooks.hooksManager.init(hooksManager.java:51) ~[?:?]
        at io.github.divios.dailyShop.hooks.hooksManager.getInstance(hooksManager.java:24) ~[?:?]
        at io.github.divios.dailyShop.DailyShop.onEnable(DailyShop.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by divios** [comment]
Hi! The bug is happening because it cannot hook to PlayerPoints. I just checked this and is working fine in my testing server with the latest version of [PlayerPoints](https://www.spigotmc.org/resources/playerpoints.80745/). What version of PlayerPoints are you using?

**Comment by 849025143** [comment]
https://mega.nz/file/Y4oEkKAB#rZrMYt4hV5FomCU7v2lT7_lPqeLWzJWfF6gSMm--IF4
It is a modified version, and many Chinese use it.
Modification from PlayerPoints 2.1.5
