### ISSUE TITLE
[bug] An error occurred executing an SQLite query

### ISSUE THREAD

**Issue by 849025143** [divios/DailyShop#60]
[12:54:55] [ForkJoinPool.commonPool-worker-5/ERROR]: [DailyShop] An error occurred executing an SQLite query: Unable to parse Malformed Json!
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]: io.github.divios.dependencies.nbt.nbtapi.NbtApiException: Unable to parse Malformed Json!
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.dependencies.nbt.nbtapi.NBTContainer.<init>(NBTContainer.java:68)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.lib.dLib.dItem.fromJson(dItem.java:722)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.lib.dLib.dItem.fromBase64(dItem.java:718)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.lib.storage.dataManager.lambda$getShop$3(dataManager.java:82)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.dependencies.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.lib.storage.dataManager.lambda$getShop$4(dataManager.java:76)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]: Caused by: io.github.divios.dependencies.nbt.nbtapi.NbtApiException: Error while calling the method 'parse', loaded: true, Enum: PARSE_NBT
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.dependencies.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:164)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.dependencies.nbt.nbtapi.NBTContainer.<init>(NBTContainer.java:66)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     ... 11 more
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at io.github.divios.dependencies.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:162)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     ... 12 more
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]: Caused by: net.minecraft.nbt.NBTException: Expected value at: ...AAoadAAIT0JTSURJQU4=
",rds_rarity:<--[HERE]
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_193602_b(SourceFile:61)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_193611_c(SourceFile:73)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_193610_d(SourceFile:164)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:190)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_193610_d(SourceFile:160)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:190)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_193609_a(SourceFile:34)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     at net.minecraft.nbt.JsonToNBT.func_180713_a(SourceFile:29)
[12:54:55] [ForkJoinPool.commonPool-worker-5/WARN]:     ... 17 more

**Comment by divios** [comment]
Hi! do you know when did this happened so I can reproduce it on my test server?
