### ISSUE TITLE
"Help here" error + internal error on reload

### ISSUE THREAD

**Issue by layagmc** [divios/DailyShop#68]
[10:20:22] [Server thread/INFO]: KurtTheFruit issued server command: /rdshop reload
[10:20:22] [Server thread/INFO]: [DailyShop] Reading lang.yml...
[10:20:22] [Server thread/INFO]: [DailyShop] No changes were made on lang.yml, skipping...
[10:20:22] [Server thread/INFO]: [DailyShop] Reading settings.yml... 
[10:20:22] [Server thread/INFO]: [DailyShop] Imported settings.yml in 2 ms
[10:20:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rdshop' in plugin DailyShop v3.6.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-77]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.github.divios.dailyShop.files.shopsResource.reload()" because "this.shopsResource" is null
	at io.github.divios.dailyShop.files.resourceManager.reload(resourceManager.java:43) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dailyShop.DailyShop.reload(DailyShop.java:76) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dailyShop.commands.reloadCommand.lambda$getCommand$0(reloadCommand.java:16) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dependencies.jCommands.JCommand.lambda$new$2(JCommand.java:31) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dependencies.jCommands.JCommandListener.callCommand(JCommandListener.java:110) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dependencies.jCommands.JCommandListener.callCommand(JCommandListener.java:124) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dependencies.jCommands.JCommandListener.onCommand(JCommandListener.java:80) ~[DailyShop-3.6.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 21 more

[10:15:51] [Server thread/WARN]: [DailyShop] Task #36 for DailyShop v3.6.4 generated an exception
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.Optional.of(Optional.java:113) ~[?:?]
	at io.github.divios.lib.managers.shopsManager.getShop(shopsManager.java:129) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dailyShop.files.shopsResource.lambda$importYamlShops$3(shopsResource.java:61) ~[DailyShop-3.6.4.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.divios.dailyShop.files.shopsResource.importYamlShops(shopsResource.java:55) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dailyShop.files.shopsResource.<init>(shopsResource.java:43) ~[DailyShop-3.6.4.jar:?]
	at io.github.divios.dailyShop.files.resourceManager.lambda$new$0(resourceManager.java:27) ~[DailyShop-3.6.4.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-77]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-77]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by divios** [comment]
Should be fixed on the new update
