### ISSUE TITLE
1.12.2  The plugin gives an error when first opened!

### ISSUE THREAD

**Issue by TeQTabanca** [divios/DailyShop#71]
**[10:03:05] [Server thread/INFO]: [DailyShop] Enabling DailyShop v3.6.0
[10:03:05] [Server thread/INFO]: Hooked to Vault
[10:03:05] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: DailyShop [3.6.0]
[10:03:05] [Server thread/INFO]: [DailyShop] Hooked to PlaceholderAPI
[10:03:05] [Thread-9/INFO]: [NBTAPI] Found Spigot: v1_12_R1! Trying to find NMS support
[10:03:05] [Thread-9/INFO]: [NBTAPI] NMS support 'MC1_12_R1' loaded!
[10:03:05] [Thread-9/INFO]: [NBTAPI] Found Gson: class com.google.gson.Gson
[10:03:06] [Thread-9/ERROR]: [DailyShop] An error occurred executing an SQLite query: Unable to parse Malformed Json!
[10:03:06] [Thread-9/WARN]: io.github.divios.dependencies.nbt.nbtapi.NbtApiException: Unable to parse Malformed Json!
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.dependencies.nbt.nbtapi.NBTContainer.<init>(NBTContainer.java:68)
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.lib.dLib.dItem.fromJson(dItem.java:712)
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.lib.dLib.dItem.fromBase64(dItem.java:708)
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.lib.storage.dataManager.lambda$getShop$3(dataManager.java:82)
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.dependencies.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.lib.storage.dataManager.lambda$getShop$4(dataManager.java:76)
[10:03:06] [Thread-9/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[10:03:06] [Thread-9/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:03:06] [Thread-9/WARN]: Caused by: java.lang.NullPointerException
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.dependencies.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180)
[10:03:06] [Thread-9/WARN]: 	at io.github.divios.dependencies.nbt.nbtapi.NBTContainer.<init>(NBTContainer.java:66)
[10:03:06] [Thread-9/WARN]: 	... 7 more
[10:03:06] [Thread-10/WARN]: [NBTAPI] The NBT-API at 'package io.github.divios.dependencies.nbt.nbtapi' seems to be a future Version, not yet released on Spigot/CurseForge!
[10:03:06] [Thread-10/WARN]: [NBTAPI] Current Version: '2.9.0-SNAPSHOT' Newest Version: 2.8.0'
[10:03:06] [Thread-8/ERROR]: Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:536) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1718) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_312]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_312]
	at io.github.divios.dependencies.Core_lib.inventory.inventoryUtils.deserialize(inventoryUtils.java:131) ~[?:?]
	at io.github.divios.dependencies.Core_lib.inventory.inventoryUtils.deserialize(inventoryUtils.java:151) ~[?:?]
	at io.github.divios.lib.dLib.dInventory._deserialize(dInventory.java:371) ~[?:?]
	at io.github.divios.lib.dLib.dInventory.<init>(dInventory.java:63) ~[?:?]
	at io.github.divios.lib.dLib.dInventory.fromBase64(dInventory.java:398) ~[?:?]
	at io.github.divios.lib.dLib.synchronizedGui.singleGui.singleGui.fromJson(singleGui.java:15) ~[?:?]
	at io.github.divios.lib.dLib.synchronizedGui.syncHashMenu.fromJson(syncHashMenu.java:22) ~[?:?]
	at io.github.divios.lib.dLib.dShop.<init>(dShop.java:69) ~[?:?]
	at io.github.divios.lib.storage.dataManager.lambda$getShops$1(dataManager.java:60) ~[?:?]
	at io.github.divios.dependencies.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54) ~[?:?]
	at io.github.divios.lib.storage.dataManager.lambda$getShops$2(dataManager.java:48) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[10:03:06] [Thread-8/ERROR]: [DailyShop] Unable to deserialize gui of shop blocks, setting it to default
[10:03:06] [Thread-8/WARN]: java.lang.IllegalStateException: Unable to deserialize inventory.
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.dependencies.Core_lib.inventory.inventoryUtils.deserialize(inventoryUtils.java:139)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.dependencies.Core_lib.inventory.inventoryUtils.deserialize(inventoryUtils.java:151)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.dLib.dInventory._deserialize(dInventory.java:371)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.dLib.dInventory.<init>(dInventory.java:63)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.dLib.dInventory.fromBase64(dInventory.java:398)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.dLib.synchronizedGui.singleGui.singleGui.fromJson(singleGui.java:15)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.dLib.synchronizedGui.syncHashMenu.fromJson(syncHashMenu.java:22)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.dLib.dShop.<init>(dShop.java:69)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.storage.dataManager.lambda$getShops$1(dataManager.java:60)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.dependencies.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.lib.storage.dataManager.lambda$getShops$2(dataManager.java:48)
[10:03:06] [Thread-8/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[10:03:06] [Thread-8/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:03:06] [Thread-8/WARN]: Caused by: java.io.IOException: Failed to deserialize object
[10:03:06] [Thread-8/WARN]: 	at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:58)
[10:03:06] [Thread-8/WARN]: 	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:50)
[10:03:06] [Thread-8/WARN]: 	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1718)
[10:03:06] [Thread-8/WARN]: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
[10:03:06] [Thread-8/WARN]: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
[10:03:06] [Thread-8/WARN]: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
[10:03:06] [Thread-8/WARN]: 	at io.github.divios.dependencies.Core_lib.inventory.inventoryUtils.deserialize(inventoryUtils.java:131)
[10:03:06] [Thread-8/WARN]: 	... 12 more
[10:03:06] [Thread-8/WARN]: Caused by: java.lang.NullPointerException
[10:03:06] [Thread-8/WARN]: 	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48)
[10:03:06] [Thread-8/WARN]: 	... 17 more**

**Comment by divios** [comment]
This is weird, did you perhaps change your version of minecraft? Is throwing an error becuase it cannot deserialize an item from the database (I'm using bukkit's api to do so, so it should work fine).

**Comment by TeQTabanca** [comment]
I didn't change the Minecraft version. I was always on 1.12.2
