### ISSUE TITLE
The logging system does not work.

### ISSUE THREAD

**Issue by GuNanOvO** [divios/DailyShop#85]
Using `/dshop log` does not display any records and outputs errors.
```
[14:07:02 INFO]: GuNanOvO issued server command: /dshop log
[14:07:02 ERROR]: [DailyShop] An error occurred executing an SQLite query: No enum constant io.github.divios.lib.dLib.log.options.dLogEntry.Type.buy
[14:07:02 WARN]: java.lang.IllegalArgumentException: No enum constant io.github.divios.lib.dLib.log.options.dLogEntry.Type.buy
[14:07:02 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:273)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.lib.dLib.log.options.dLogEntry$Type.valueOf(dLogEntry.java:257)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.lib.storage.databaseManager.lambda$getLogEntries$27(databaseManager.java:339)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.dependencies.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:54)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.lib.storage.databaseManager.getLogEntries(databaseManager.java:317)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.lib.dLib.log.LogGui.lambda$init$3(LogGui.java:45)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.dependencies.Core_lib.inventory.builder.paginatedGui.init(paginatedGui.java:85)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.dependencies.Core_lib.inventory.builder.paginatedGui.<init>(paginatedGui.java:55)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.dependencies.Core_lib.inventory.builder.paginatedGui.<init>(paginatedGui.java:26)
[14:07:02 WARN]:        at DailyShop-3.6.6.jar//io.github.divios.dependencies.Core_lib.inventory.builder.paginatedGui$BuilderImpl.build(paginatedGui.java:224)
[14:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
Could you add an action that closes the menu?
https://github.com/divios/DailyShop/wiki/actions

**Comment by divios** [comment]
Hi!
You are right, [this build](https://we.tl/t-3cr7rJdbbj) fix this and also adds the `CLOSE_INVENTORY` action
