### ISSUE TITLE
ava.lang.NullPointerException: Cannot invoke "io.github.divios.lib.dLib.dItem.hasStock()" because "item" is null

### ISSUE THREAD

**Issue by l3unnyAnoF4** [divios/DailyShop#9]
[10:43:57 WARN]: java.lang.NullPointerException: Cannot invoke "io.github.divios.lib.dLib.dItem.hasStock()" because "item" is null
[10:43:57 WARN]:        at DailyShop-3.4.jar//io.github.divios.dailyShop.transaction.transaction.init(transaction.java:40)
[10:43:57 WARN]:        at DailyShop-3.4.jar//io.github.divios.lib.dLib.dInventory.lambda$ready$12(dInventory.java:307)
[10:43:57 WARN]:        at DailyShop-3.4.jar//io.github.divios.dailyShop.shaded.Core_lib.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:120)
[10:43:57 WARN]:        at DailyShop-3.4.jar//io.github.divios.dailyShop.shaded.Core_lib.event.functional.single.HelperEventListener.execute(HelperEventListener.java:134)
[10:43:57 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[10:43:57 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:43:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[10:43:57 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2810)
[10:43:57 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[10:43:57 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[10:43:57 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[10:43:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[10:43:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[10:43:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[10:43:57 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1423)
[10:43:57 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1416)
[10:43:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:135)
[10:43:57 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1389)
[10:43:57 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1299)
[10:43:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[10:43:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by divios** [comment]
Hi! When did this happen?

**Comment by l3unnyAnoF4** [comment]
I don't remember, but it's okay now.

**Comment by l3unnyAnoF4** [comment]
when open shop
![image](https://user-images.githubusercontent.com/67956962/132118540-079061a8-4c94-470f-8125-b0abbc5e75d9.png)

**Comment by divios** [comment]
I just found the error that was cousing this, this afternoon i'll update the fix with some other bugs that i have to check

**Comment by divios** [comment]
Check the new update, it fixes this error

**Comment by l3unnyAnoF4** [comment]
Thx sir
