### ISSUE TITLE
Bugggg

### ISSUE THREAD

**Issue by mani1232** [divios/DailyShop#92]
[14:05:10 INFO]: mani123 issued server command: /dailyshop reload
[14:05:10 INFO]: [DailyShop] Reading lang.yml...
[14:05:10 INFO]: [DailyShop] Imported lang.yml in 5 ms
[14:05:10 INFO]: [DailyShop] Reading settings.yml...
[14:05:10 INFO]: [DailyShop] No changes were made in settings.yml, skipping...
[14:05:10 INFO]: [DailyShop] Importing data from shops directory...
[14:05:10 INFO]: [DailyShop] Updated shop of name блоки with 1 items
[14:05:10 INFO]: [DailyShop] Data imported successfully in 14 ms
[14:05:10 INFO]: [DailyShop] Reading priceModifiers.yml...
[14:05:10 INFO]: [DailyShop] No changes were made in priceModifier.yml, skipping...
[14:05:14 INFO]: mani123 issued server command: /dailyshop reStock
[14:05:14 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dailyshop' in plugin DailyShop v3.6.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2187) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1441) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1389) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at io.github.divios.jcommands.JCommandListener.wrapArgs(JCommandListener.java:84) ~[DailyShop-3.6.9.jar:?]
        at io.github.divios.jcommands.JCommandListener.onCommand(JCommandListener.java:68) ~[DailyShop-3.6.9.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more
>

Fix it pls

**Comment by divios** [comment]
Hi! thanks for reporting it. Is true that this is a bug but, **/ds restock** is not used like that, you have to add the name of the shop you want to restock, for example **/ds restock drops**

**Comment by mani1232** [comment]
OK thanks

**Comment by divios** [comment]
Fixed on new release
